"""make_goal_dates_optional_and_remove_unnecessary_fields

Revision ID: 9af49871a6c8
Revises: 
Create Date: 2025-12-01 09:17:33.973396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9af49871a6c8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Make start_date and end_date nullable
    op.alter_column('goals', 'start_date',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('goals', 'end_date',
               existing_type=sa.DATE(),
               nullable=True)

    # Remove unnecessary fields
    op.drop_column('goals', 'evaluation_method')
    op.drop_column('goals', 'difficulty_level')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the removed columns
    op.add_column('goals', sa.Column('difficulty_level', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('goals', sa.Column('evaluation_method', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # Make dates non-nullable again (note: this may fail if there are NULL values)
    op.alter_column('goals', 'end_date',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('goals', 'start_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
