"""Add PENDING_ACTIVATION status to UserStatus enum

Revision ID: cc7410bd0a08
Revises: b3d53f692103
Create Date: 2025-12-03 12:48:47.503384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc7410bd0a08'
down_revision: Union[str, None] = 'b3d53f692103'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes and tables only if they exist (for backward compatibility)
    op.execute('DROP INDEX IF EXISTS ix_task_documents_id')
    op.execute('DROP TABLE IF EXISTS task_documents CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_task_extensions_id')
    op.execute('DROP TABLE IF EXISTS task_extensions CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_task_assignments_id')
    op.execute('DROP TABLE IF EXISTS task_assignments CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_task_submissions_id')
    op.execute('DROP TABLE IF EXISTS task_submissions CASCADE')
    op.execute('DROP INDEX IF EXISTS ix_tasks_id')
    op.execute('DROP TABLE IF EXISTS tasks CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('type', postgresql.ENUM('INDIVIDUAL', 'GROUP', name='tasktype'), autoincrement=False, nullable=False),
    sa.Column('urgency', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='taskurgency'), autoincrement=False, nullable=True),
    sa.Column('due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'ONGOING', 'COMPLETED', 'PENDING_REVIEW', 'APPROVED', 'OVERDUE', name='taskstatus'), autoincrement=False, nullable=True),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('team_head_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('goal_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='tasks_created_by_fkey'),
    sa.ForeignKeyConstraint(['goal_id'], ['goals.id'], name='tasks_goal_id_fkey'),
    sa.ForeignKeyConstraint(['team_head_id'], ['users.id'], name='tasks_team_head_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='tasks_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_tasks_id', 'tasks', ['id'], unique=False)
    op.create_table('task_submissions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('report', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('submitted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('submitted_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['submitted_by'], ['users.id'], name='task_submissions_submitted_by_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_submissions_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_submissions_pkey')
    )
    op.create_index('ix_task_submissions_id', 'task_submissions', ['id'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_assignments_task_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='task_assignments_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_assignments_pkey')
    )
    op.create_index('ix_task_assignments_id', 'task_assignments', ['id'], unique=False)
    op.create_table('task_extensions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('new_due_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('PENDING', 'APPROVED', 'DENIED', name='extensionstatus'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('requested_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('reviewed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], name='task_extensions_requested_by_fkey'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name='task_extensions_reviewed_by_fkey'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_extensions_task_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_extensions_pkey')
    )
    op.create_index('ix_task_extensions_id', 'task_extensions', ['id'], unique=False)
    op.create_table('task_documents',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('uploaded_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('task_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('uploaded_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name='task_documents_task_id_fkey'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name='task_documents_uploaded_by_fkey'),
    sa.PrimaryKeyConstraint('id', name='task_documents_pkey')
    )
    op.create_index('ix_task_documents_id', 'task_documents', ['id'], unique=False)
    # ### end Alembic commands ###
